### ISSUE TITLE
Which python version?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/dwd-radolan-tree-harvester#1]
Which which which?

**Comment by sebastian-meier** [comment]
3.8.1 
I pushed my https://github.com/technologiestiftung/dwd-radolan-tree-harvester/blob/master/pyvenv.cfg (i should have probably added this to the .gitignore?!

**Comment by fabianmoronzirfas** [comment]
Yes. I guess so. I'll try to build an image based on debian with a ready made python version. No need for a venv
